<a href="https://colab.research.google.com/github/yonghoonlee-1/Graph-and-Networks-Analysis/blob/main/popularity_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
!rm -rf /content/gdrive
!ln -s "/gdrive/My Drive" /content/gdrive
%cd /content/gdrive

Mounted at /gdrive
/gdrive/My Drive


In [ ]:
import numpy as np

class_info = np.loadtxt('/content/gdrive/class_info.txt')
edge_list = np.loadtxt('/content/gdrive/edge_list.txt')

In [ ]:
print(class_info)

[[   1.    0.]
 [   2.    0.]
 [   3.    0.]
 ...
 [ 998.    0.]
 [ 999.    1.]
 [1000.    0.]]


In [ ]:
print(edge_list)

[[411. 545.]
 [411. 838.]
 [411. 144.]
 ...
 [942. 821.]
 [782. 144.]
 [423.   3.]]


In [ ]:
pip install node2vec

  Created wheel for node2vec: filename=node2vec-0.4.0-cp36-none-any.whl size=5729 sha256=01a1099156c198117178836467019e447bad4e39560f7dc1986e37d05d2f131e
  Stored in directory: /root/.cache/pip/wheels/68/64/b9/599a860e730d0a4c633db99e5dcd8c4beee4ff9e3d5b3a011a
Successfully built node2vec


In [ ]:
import networkx as nx
from node2vec import Node2Vec

G = nx.Graph()

for i in range(1, 1001):
    G.add_node(str(i))

In [ ]:
for i in range(len(edge_list)):
    G.add_edge(str(int(edge_list[i][0])), str(int(edge_list[i][1])))

In [ ]:
print("Number of Nodes : ", nx.number_of_nodes(G))

Number of Nodes :  1000


In [ ]:
print("Number of Edges : ", nx.number_of_edges(G))

Number of Edges :  6821


In [ ]:
G.nodes()

NodeView(('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157',

In [ ]:
node2vec = Node2Vec(G, dimensions=50, walk_length=16, num_walks=100, workers=2)

In [ ]:
model = node2vec.fit(window=10, min_count=1)

In [ ]:
for node, _ in model.most_similar('6'):
    print(node)

942
874
501
982
27
61
146
345
31
937


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


In [ ]:
for i in enumerate(model.wv.vocab):
  print(i)

(0, '598')
(1, '238')
(2, '397')
(3, '144')
(4, '72')
(5, '600')
(6, '625')
(7, '14')
(8, '415')
(9, '870')
(10, '717')
(11, '439')
(12, '90')
(13, '352')
(14, '933')
(15, '456')
(16, '282')
(17, '831')
(18, '991')
(19, '688')
(20, '673')
(21, '164')
(22, '634')
(23, '287')
(24, '268')
(25, '544')
(26, '538')
(27, '751')
(28, '354')
(29, '848')
(30, '491')
(31, '273')
(32, '987')
(33, '838')
(34, '299')
(35, '545')
(36, '800')
(37, '946')
(38, '753')
(39, '332')
(40, '907')
(41, '542')
(42, '575')
(43, '351')
(44, '480')
(45, '836')
(46, '369')
(47, '801')
(48, '1000')
(49, '686')
(50, '585')
(51, '908')
(52, '128')
(53, '1')
(54, '46')
(55, '425')
(56, '278')
(57, '846')
(58, '328')
(59, '530')
(60, '759')
(61, '742')
(62, '840')
(63, '422')
(64, '476')
(65, '163')
(66, '917')
(67, '135')
(68, '785')
(69, '629')
(70, '450')
(71, '355')
(72, '388')
(73, '586')
(74, '767')
(75, '851')
(76, '11')
(77, '619')
(78, '805')
(79, '812')
(80, '269')
(81, '884')
(82, '807')
(83, '308')
(84, '70

In [ ]:
embeddings = np.array([model.wv[x] for x in G.nodes()])

In [ ]:
embeddings[0]

array([-1.3662302 ,  0.64186174,  0.7066973 ,  0.6740783 , -0.46378464,
       -0.671847  ,  0.1804852 ,  1.0216119 ,  1.8648512 , -1.7315998 ,
        0.6063655 , -0.24417485, -0.4941088 ,  1.1060463 , -1.4236346 ,
        1.7215463 , -0.03180356, -1.7289431 ,  1.4170915 ,  0.12475399,
       -0.43824393,  1.7213844 , -1.4014282 ,  0.36821777,  0.58135873,
       -1.5673398 , -0.19013628,  0.7286083 , -1.7594006 , -1.2201906 ,
       -1.799435  , -1.2584752 , -0.75913453,  0.17016853, -1.6604791 ,
       -1.5846109 ,  1.1865467 , -0.3774186 , -1.1834745 , -1.264107  ,
        0.40730008,  0.3493626 ,  0.65821   , -0.4808393 ,  0.78264195,
       -0.5425674 , -1.4345397 , -0.3163706 , -1.4679469 , -1.0910413 ],
      dtype=float32)

In [ ]:
embeddings[999]

array([-1.1292435 , -0.32597834, -0.57567906,  0.21491702,  0.16022459,
        0.12471286,  2.720416  , -0.18788904,  2.930375  , -1.0764867 ,
       -1.9213643 , -1.6688936 ,  0.09228498,  2.280279  , -0.38299143,
        0.07026184,  0.41173238, -1.5007651 , -3.0956924 ,  0.44493273,
        2.5716863 , -0.2894061 , -1.0304661 ,  2.0928845 , -0.0710726 ,
       -1.7062846 , -0.09385163, -0.10065977, -0.10619459,  1.273177  ,
       -0.9860927 ,  0.8172613 , -2.2096796 , -2.2214463 ,  2.4076068 ,
       -0.6592381 ,  0.55493724, -1.7407883 ,  0.27092624, -0.2877807 ,
       -1.074796  ,  1.5971209 , -1.9145766 ,  2.3993814 ,  0.42618823,
        0.9631849 , -1.0022726 ,  1.3943774 , -0.50127107,  0.01237984],
      dtype=float32)

In [ ]:
from numpy import zeros

embedding_matrix = zeros((1001, 50))

In [ ]:
for i in range(1, 1001):
  embedding_matrix[i] = embeddings[i-1]

In [ ]:
embedding_matrix[1]

array([-1.36623025,  0.64186174,  0.70669729,  0.67407829, -0.46378464,
       -0.67184699,  0.1804852 ,  1.02161193,  1.86485124, -1.73159981,
        0.6063655 , -0.24417485, -0.4941088 ,  1.10604632, -1.42363465,
        1.72154629, -0.03180356, -1.72894311,  1.41709149,  0.12475399,
       -0.43824393,  1.72138441, -1.40142822,  0.36821777,  0.58135873,
       -1.56733978, -0.19013628,  0.72860831, -1.75940061, -1.22019064,
       -1.79943502, -1.25847518, -0.75913453,  0.17016853, -1.66047907,
       -1.58461094,  1.18654668, -0.37741861, -1.18347454, -1.26410699,
        0.40730008,  0.34936261,  0.65820998, -0.48083931,  0.78264195,
       -0.54256737, -1.43453968, -0.31637061, -1.46794689, -1.09104133])

In [ ]:
embedding_matrix[1000]

array([-1.12924349, -0.32597834, -0.57567906,  0.21491702,  0.16022459,
        0.12471286,  2.72041607, -0.18788904,  2.9303751 , -1.07648671,
       -1.92136431, -1.66889358,  0.09228498,  2.28027892, -0.38299143,
        0.07026184,  0.41173238, -1.50076509, -3.0956924 ,  0.44493273,
        2.57168627, -0.28940609, -1.03046608,  2.09288454, -0.0710726 ,
       -1.70628464, -0.09385163, -0.10065977, -0.10619459,  1.27317703,
       -0.98609269,  0.81726128, -2.2096796 , -2.22144628,  2.40760684,
       -0.6592381 ,  0.55493724, -1.74078834,  0.27092624, -0.2877807 ,
       -1.07479596,  1.59712088, -1.91457665,  2.3993814 ,  0.42618823,
        0.96318489, -1.00227261,  1.39437735, -0.50127107,  0.01237984])

In [ ]:
popular = []
un_popular = []
unknown = []
train = []
train_label = []
test = []

for i in range(len(class_info)):
    if class_info[i][1]== 1:
        popular.append(str(i+1))
        train.append(i+1)
        train_label.append(1)
    elif class_info[i][1]== -1:
        un_popular.append(str(i+1))
        train.append(i+1)
        train_label.append(0)
    else:
        unknown.append(str(i+1))
        test.append(i+1)

In [ ]:
train = np.array(train)

In [ ]:
test = np.array(test)

In [ ]:
print(train)

[  6   7   9  15  16  17  19  26  31  33  36  38  41  54  62  63  71  73
  84  88  89  97 101 103 112 115 117 118 120 122 136 141 150 155 162 163
 165 170 173 174 183 192 194 198 205 212 213 215 220 229 231 235 236 240
 242 243 260 261 269 277 279 284 288 289 300 312 324 326 330 331 333 351
 354 358 363 372 373 374 375 377 386 389 409 410 415 419 420 421 423 431
 438 445 448 450 452 453 454 460 464 467 468 470 482 486 492 494 501 505
 514 517 518 527 528 530 535 538 539 541 543 544 549 566 572 573 579 580
 583 586 601 605 609 610 614 616 627 633 637 642 643 656 681 682 683 684
 685 687 693 705 715 722 728 740 746 757 758 759 760 763 767 769 774 796
 807 824 826 834 836 850 853 857 858 860 863 865 878 890 893 895 897 901
 909 910 911 912 916 926 928 942 947 951 955 971 972 973 975 977 981 990
 997 999]


In [ ]:
print(test)

[   1    2    3    4    5    8   10   11   12   13   14   18   20   21
   22   23   24   25   27   28   29   30   32   34   35   37   39   40
   42   43   44   45   46   47   48   49   50   51   52   53   55   56
   57   58   59   60   61   64   65   66   67   68   69   70   72   74
   75   76   77   78   79   80   81   82   83   85   86   87   90   91
   92   93   94   95   96   98   99  100  102  104  105  106  107  108
  109  110  111  113  114  116  119  121  123  124  125  126  127  128
  129  130  131  132  133  134  135  137  138  139  140  142  143  144
  145  146  147  148  149  151  152  153  154  156  157  158  159  160
  161  164  166  167  168  169  171  172  175  176  177  178  179  180
  181  182  184  185  186  187  188  189  190  191  193  195  196  197
  199  200  201  202  203  204  206  207  208  209  210  211  214  216
  217  218  219  221  222  223  224  225  226  227  228  230  232  233
  234  237  238  239  241  244  245  246  247  248  249  250  251  252
  253 

In [ ]:
print(train_label)

[1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1]


In [ ]:
from keras.utils import to_categorical

train_label = to_categorical(train_label)

print(train_label)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_val, Y_train, Y_val = train_test_split(train, train_label, test_size = 0.1, random_state=321)

X_train.shape, X_val.shape, Y_train.shape, Y_val.shape 

((180,), (20,), (180, 2), (20, 2))

In [ ]:
X_train = np.expand_dims(X_train, -1)

In [ ]:
X_train.shape

(180, 1)

In [ ]:
X_val = np.expand_dims(X_val, -1)

In [ ]:
test = np.expand_dims(test, -1)

In [ ]:
test.shape

(800, 1)

In [ ]:
from keras.layers import Embedding, Dense, Dropout, Flatten
from keras.layers.convolutional import Conv1D
from keras.models import Sequential

embed_dim = 50

model = Sequential()
model.add(Embedding(1000 + 1, embed_dim, weights=[embedding_matrix], input_length = X_train.shape[1]))
model.add(Conv1D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(2,activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1, 50)             50050     
_________________________________________________________________
conv1d (Conv1D)              (None, 1, 128)            19328     
_________________________________________________________________
dropout (Dropout)            (None, 1, 128)            0         
_________________________________________________________________
flatten (Flatten)            (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 2)                 258       
Total params: 69,636
Trainable params: 69,636
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
history = model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=50, batch_size=128)

Epoch 1/50
2/2 [==============================] - 0s 95ms/step - loss: 0.8438 - accuracy: 0.5222 - val_loss: 0.8671 - val_accuracy: 0.4500
Epoch 2/50
2/2 [==============================] - 0s 9ms/step - loss: 0.7367 - accuracy: 0.5556 - val_loss: 0.7288 - val_accuracy: 0.5000
Epoch 3/50
2/2 [==============================] - 0s 9ms/step - loss: 0.6475 - accuracy: 0.6278 - val_loss: 0.6153 - val_accuracy: 0.5500
Epoch 4/50
2/2 [==============================] - 0s 9ms/step - loss: 0.5969 - accuracy: 0.6944 - val_loss: 0.5226 - val_accuracy: 0.8000
Epoch 5/50
2/2 [==============================] - 0s 9ms/step - loss: 0.5157 - accuracy: 0.7278 - val_loss: 0.4509 - val_accuracy: 0.9000
Epoch 6/50
2/2 [==============================] - 0s 10ms/step - loss: 0.5191 - accuracy: 0.7611 - val_loss: 0.3930 - val_accuracy: 0.9000
Epoch 7/50
2/2 [==============================] - 0s 9ms/step - loss: 0.4761 - accuracy: 0.8167 - val_loss: 0.3467 - val_accuracy: 0.9000
Epoch 8/50
2/2 [================

In [ ]:
predict_val = (model.predict(X_val) >= 0.5) 

In [ ]:
from sklearn import metrics

print('Accuracy:\n',
      metrics.accuracy_score(Y_val, predict_val))

Accuracy:
 1.0
